//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.mini.pw.edu.pl/ucc/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.mini.pw.edu.pl/ucc/", IsNullable = false)]
public partial class RegisterResponse
{

    private string idField;

    private string timeoutField;

    private RegisterResponseBackupCommunicationServersBackupCommunicationServer[] backupCommunicationServersField;

    /// <uwagi/>
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <uwagi/>
    public string Timeout
    {
        get
        {
            return this.timeoutField;
        }
        set
        {
            this.timeoutField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("BackupCommunicationServer", typeof(RegisterResponseBackupCommunicationServersBackupCommunicationServer), IsNullable = false)]
    public RegisterResponseBackupCommunicationServersBackupCommunicationServer[] BackupCommunicationServers
    {
        get
        {
            return this.backupCommunicationServersField;
        }
        set
        {
            this.backupCommunicationServersField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.mini.pw.edu.pl/ucc/")]
public partial class RegisterResponseBackupCommunicationServersBackupCommunicationServer
{

    private string addressField;

    private string portField;

    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string port
    {
        get
        {
            return this.portField;
        }
        set
        {
            this.portField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.mini.pw.edu.pl/ucc/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.mini.pw.edu.pl/ucc/", IsNullable = false)]
public partial class NewDataSet
{

    private RegisterResponse[] itemsField;

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("RegisterResponse")]
    public RegisterResponse[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}