//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.8009
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using ClusterMessages;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.mini.pw.edu.pl/ucc/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.mini.pw.edu.pl/ucc/", IsNullable = false)]
public partial class NoOperation : IClusterMessage
{

    private NoOperationBackupCommunicationServers backupCommunicationServersField;

    /// <uwagi/>
    public NoOperationBackupCommunicationServers BackupCommunicationServers
    {
        get
        {
            return this.backupCommunicationServersField;
        }
        set
        {
            this.backupCommunicationServersField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.mini.pw.edu.pl/ucc/")]
public partial class NoOperationBackupCommunicationServers
{

    private NoOperationBackupCommunicationServersBackupCommunicationServer backupCommunicationServerField;

    /// <uwagi/>
    public NoOperationBackupCommunicationServersBackupCommunicationServer BackupCommunicationServer
    {
        get
        {
            return this.backupCommunicationServerField;
        }
        set
        {
            this.backupCommunicationServerField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.mini.pw.edu.pl/ucc/")]
public partial class NoOperationBackupCommunicationServersBackupCommunicationServer
{

    private string addressField;

    private ushort portField;

    private bool portFieldSpecified;

    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort port
    {
        get
        {
            return this.portField;
        }
        set
        {
            this.portField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool portSpecified
    {
        get
        {
            return this.portFieldSpecified;
        }
        set
        {
            this.portFieldSpecified = value;
        }
    }
}
